version: '3.9'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
      - ./init-keyspace.cql:/docker-entrypoint-initdb.d/init-keyspace.cql
    environment:
      - CASSANDRA_CLUSTER_NAME=test
      - CASSANDRA_KEYSPACE=test
