version: '3.9'

services:
  cassandra:
    image: cassandra:4.1@sha256:2a58bdfe124aa239a1846a6330b8f52bfd4321726995269382ab925fef74bd71
    ports:
      - 9042:9042
    volumes:
      - cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - CASSANDRA_CLUSTER_NAME=test
    
  api:
    image: ghcr.io/kilianp07/cassandracrud:latest
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra

volumes:
  cassandra:

