version: '3.9'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
      - ./init-keyspace.cql:/docker-entrypoint-initdb.d/init-keyspace.cql
    
  api:
    image: ghcr.io/kilianp07/cassandracrud:latest
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra


